#!/usr/bin/env bash
# Summary: Configure the shell environment for pyenv
# Usage: eval "$(pyenv init - [--no-rehash] [<shell>])"

set -e
[ -n "$PYENV_DEBUG" ] && set -x

# Provide pyenv completions
if [ "$1" = "--complete" ]; then
  echo -
  echo --no-rehash
  echo bash
  echo fish
  echo ksh
  echo zsh
  echo xonsh
  exit
fi

print=""
no_rehash=""
for args in "$@"
do
  if [ "$args" = "-" ]; then
    print=1
    shift
  fi

  if [ "$args" = "--no-rehash" ]; then
    no_rehash=1
    shift
  fi
done

shell="$1"
if [ -z "$shell" ]; then
  shell="$(ps -p "$PPID" -o 'args=' 2>/dev/null || true)"
  shell="${shell%% *}"
  shell="${shell##-}"
  shell="${shell:-$SHELL}"
  shell="${shell##*/}"
fi

root="${0%/*}/.."

if [ -z "$print" ]; then
  case "$shell" in
  bash )
    if [ -f "${HOME}/.bashrc" ] && [ ! -f "${HOME}/.bash_profile" ]; then
      profile='~/.bashrc'
    else
      profile='~/.bash_profile'
    fi
    ;;
  zsh )
    profile='~/.zshrc'
    ;;
  ksh )
    profile='~/.profile'
    ;;
  fish )
    profile='~/.config/fish/config.fish'
    ;;
  xonsh )
    profile='~/.xonshrc'
    ;;
  * )
    profile='your profile'
    ;;
  esac

  { echo "# Load pyenv automatically by appending"
    echo "# the following to ${profile}:"
    echo
    case "$shell" in
    fish )
      echo 'status --is-interactive; and source (pyenv init -|psub)'
      ;;
    xonsh )
      echo "pyenv init - --no-rehash > ${PYENV_ROOT}/cache/init.xsh"
      echo "source ${PYENV_ROOT}/cache/init.xsh"
      ;;
    * )
      echo 'eval "$(pyenv init -)"'
      ;;
    esac
    echo
  } >&2

  exit 1
fi

mkdir -p "${PYENV_ROOT}/"{shims,versions}

case "$shell" in
fish )
  echo "set -gx PATH '${PYENV_ROOT}/shims' \$PATH"
  echo "set -gx PYENV_SHELL $shell"
;;
xonsh )
  echo "\$PATH.insert(0, '${PYENV_ROOT}/shims')"
  echo "\$PYENV_SHELL = '$shell'"
;;
* )
  echo 'export PATH="'${PYENV_ROOT}'/shims:${PATH}"'
  echo "export PYENV_SHELL=$shell"
;;
esac

completion="${root}/completions/pyenv.${shell}"
if [ -r "$completion" ]; then
  echo "source '$completion'"
fi

if [ -z "$no_rehash" ]; then
  echo 'command pyenv rehash 2>/dev/null'
fi

commands=(`pyenv-commands --sh`)
case "$shell" in
fish )
  cat <<EOS
function pyenv
  set command \$argv[1]
  set -e argv[1]

  switch "\$command"
  case ${commands[*]}
    source (pyenv "sh-\$command" \$argv|psub)
  case '*'
    command pyenv "\$command" \$argv
  end
end
EOS
  ;;
ksh )
  cat <<EOS
function pyenv {
  typeset command
EOS
  ;;
xonsh )
  cat <<EOS
import shlex
def _pyenv(args, stdin=None, stdout=None, stderr=None, spec=None):
   if not args:
      command pyenv
      return
   chosen_command = args[0]
   extra_args = ' '.join([shlex.quote(a) for a in args[1:]])
   if chosen_command in "${commands[*]}".split(' '):
      source-bash \$(pyenv @(f'sh-{chosen_command}') @(extra_args))
   else:
      command pyenv @(chosen_command) @(extra_args)
aliases["pyenv"] = _pyenv
EOS
  ;;
* )
  cat <<EOS
pyenv() {
  local command
EOS
  ;;
esac

if [ "$shell" != "fish" ] && [ "$shell" != "xonsh" ]; then
IFS="|"
cat <<EOS
  command="\${1:-}"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  ${commands[*]})
    eval "\$(pyenv "sh-\$command" "\$@")";;
  *)
    command pyenv "\$command" "\$@";;
  esac
}
EOS
fi
